apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvone
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/tmp/"
